services:
    _defaults:
        public: true

    persistent_cache_item_pool:
        class: \Symfony\Component\Cache\Adapter\FilesystemAdapter
    request_cache_item_pool:
        class: \Symfony\Component\Cache\Adapter\ArrayAdapter